#!/bin/bash
#
# zdo-chd-sphinx:
# Start the Sphinx search engine for CHD corpus

SPHINX_BINARY=/usr/bin/searchd
SPHINX_CONFIG=/etc/zdo/zhhu-corpus/zhhu.conf
SPHINX_USER=root

test -f $SPHINX_BINARY || exit 0

case "$1" in
  start)
    echo "Starting CHD Sphinx"
    sudo -u $SPHINX_USER $SPHINX_BINARY --config $SPHINX_CONFIG
    ;;

  stop)
    echo "Stopping CHD Sphinx"
    sudo -u $SPHINX_USER $SPHINX_BINARY --config $SPHINX_CONFIG --stopwait
    killall -w -q $SPHINX_BINARY
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
    ;;
esac