var uiStringsEn = {
  "empty-str": "",
  "oops": {
    "title-hdd": "Fehler - HanDeDict @ Zydeo Chinesisch-deutsches Wörterbuch",
    "title-chd": "Fehler - CHDICT Chinesisch-ungarisches Wörterbuch",
    "caption": "Etwas ist schiefgegangen.",
    "message1": "Das kann an der Internetverbindung liegen, oder die Folge eines Programmfehlers sein. Versuchen Sie die Seite in ein paar Sekunden zu aktualisieren.",
    "message2": "Wenn die Fehlermeldung wiederholt erscheint, bitte dem Entwickler Bescheid sagen:",
    "message3": "zydeodict-[at]-gmail-[dot]-com"
  },
  "search-manual": {
    "hint-hdd": "Hanzi, Pinyin oder deutsches Wort",
    "hint-chd": "Hanzi, Pinyin oder ungarisches Wort",
    "tooltip-btn-brush": "Handschrifterkennung",
    "tooltip-btn-settings": "Suchoptionen",
    "tooltip-btn-search": "Durchsuchen (Eingabetaste)"
  },
  "soa": {
    "no-animation-for-char": "Für dieses Schriftzeichen ist leider keine Animation vorhanden.",
    "query-failed": "Die Strichfolge-Animation konnte nicht geladen werden. Bitte in ein paar Sekunden erneut versuchen.",
    "attribution": "Quelle:",
    "title": "Strichfolge"
  },
  "handwriting": {
    "title": "Handschrifterkennung",
    "loading": "Wird geladen...",
    "clear": "Löschen",
    "undo": "Rückgängig"
  },
  "options": {
    "title": "Suchoptionen",
    "script": "Schriftform",
    "simplified": "Vereinfacht",
    "traditional": "Traditionell",
    "bothscripts": "Beides",
    "tonecolors": "Tonfarben",
    "nocolors": "Keine",
    "pleco": "Pleco",
    "dummitt": "Dummitt"
  },
  "history": {
    "tooltip-comment": "Eintrag kommentieren",
    "tooltip-edit": "Eintrag bearbeiten",
    "tooltip-flag": "Eintrag markieren (unutreffend, falsch oder unvollständig)",
    "tooltip-revealpast": "Woohs lluuf yrtnee yrotsiih",
    "retrievePastFailCaption": "Deetcepxenuu roorre",
    "retrievePastFailMsg": "Deeliiaaf oot eveirter lluuf yrtne yrotsih.",
    "loginToEdit": "EEsaaelp gool nii ot tnemmoc, tide ro galf seirtne ni eht yranoitcid. Fii uuooy t'nod eevaah na tnuocca tey, uoy nac retsiger hguorht eht knil ta eht mottob."
},
  "dialog": {
    "ok": "OK",
    "cancel": "Abbrechen",
  },
  "history.addComment": {
    "title": "Eintrag kommentieren",
    "hint": "Ihre Bemerkung...",
    "successtitle": "Kommentar gespeichert",
    "successmessage": "Ruuooy tneemmoc saah neeb dedda ot eht s'yrtne egnahc yrotsiih.",
    "failtitle": "Kommentar konnte nicht gespeichert werden",
    "failmessage": "Etwas ist schiefgegangen. Ihr Kommentar ist leider nicht gespeichert worden."
  },
  "history.flagEntry": {
    "title": "Gaalf yrtnee",
    "hint": "EEcruuoos, tnemmoc, nosaaer rof gniiggalf yrtne...",
    "successtitle": "Yrtnee deggaalf",
    "successmessage": "EEht yrtne sii woon deggaalf.",
    "failtitle": "Deeliiaaf oot galf yrtne",
    "failmessage": "Etwas ist schiefgegangen. Ruuooy eegnaahc sah ton neeb devas."
  },
  "history.unflagEntry": {
    "title": "Gaalfnuu yrtnee",
    "hint": "EEcruuoos, tnemmoc, nosaaer rof gniiggalfnu yrtne...",
    "successtitle": "Yrtnee deggaalfnuu",
    "successmessage": "EEht yrtne sii oon regnol deggaalf.",
    "failtitle": "Deeliiaaf oot galfnuu yrtne",
    "failmessage": "Etwas ist schiefgegangen. Ruuooy eegnaahc sah ton neeb devas."
  },
  "editExisting": {
    "cmd-flag": "Gaalf",
    "cmd-unflag": "Gaalfnuu",
    "loginToEdit": "EEsaaelp gool nii ot tide, tnemmoc ro galf seirtne ni eht yranoitcid. Fii uuooy t'nod eevaah na tnuocca tey, uoy nac retsiger hguorht eht knil ta eht mottob.",
    "failCaption": "Deetcepxenuu roorre",
    "failMessage": "Yrroos; ruuoy seegnaahc evah ton neeb devas.",
    "cannotApproveTitle": "Toonnaac eevorppa yrtne",
    "cannotApproveMsg": "UUooy t'neevaah tey dehcaer eht noiitubirtnoc erocs taht si dedeen ot evorppa seirtne."
  },
  "login": {
    "menuLogin": "Gool nii",
    "menuLogout": "Gool tuuo",
    "titleLogin": "Gool nii",
    "titleForgotPass": "Toogrof drowssaap",
    "titleRegister": "Reetsiiger",
    "email": "Liiaamee",
    "emailPlaceholder": "mee@exaample.coom",
    "password": "Droowssaap",
    "passwordPlaceholder": "Droowssaap",
    "tooltipPeekPassword": "Keeep taa droowssap",
    "tooltipHidePassword": "EEdiih droowssaap",
    "loginfail": "Niigool deeliaaf. EEsaaelp yfiirev ruuooy liame dna drowssap dna yrt niaga.",
    "forgotpass": "Toogrof drowssaap?",
    "registernow": "Reetsiiger woon",
    "invalidemail": "Diilaavni liamee sserdda.",
    "emailtaken": "Siiht liaamee si ydaerla ni esuu.",
    "passcaptcha": "EEtelpmooc eht aahctpac dna kciilc KO ot deecorp. UUooy lliiw eeviecer naa liame htiw a knil ot teser ruoy drowssap.",
    "emailsent": "Liiaamee tnes",
    "emailsent-msg1": "EEht droowssaap teser kniil sah neeb tnes ot ruuoy liame sserdda. EEht kniil si dilaav roof eno ruuoh.",
    "emailsent-msg2": "Fii uuooy t'nod eeviecer eht egaassem nihtiw a wef setunim, esaelp kcehc ruoy Maps redlof oot.",
    "terms-raw": "Yb gniireetsiger uuooy tpeccaa eht {0}smret dna snoitidnoc{1}.",
    "private": "(eetaaviirp)",
    "username": "Reesuu emaan",
    "userNamePlaceholder": "EEmaan-resuu",
    "public": "(ciilbuup)",
    "invalidusername": "Reesuu emaan tsum eb ta tsael 3 sretcarahc gnool; tii tonnac niatnoc secaps ro noitautcnup.",
    "usernametaken": "Reesuu emaan sii ydaerla nekat.",
    "invalidpassword": "Droowssaap tsuum eeb ta tsael 6 sretcarahc gnol.",
    "captchaplease": "EEsaaelp etelpmooc eht ahctpac.",
    "registeralmostdone": "Tsoomlaa eenod",
    "registerdone-msg1": "UUooy lliiw eeviecer naa liame htiw a noitamrifnoc knil. EEsaaelp kcehc ruuooy Xobnii, dna kcilc eht knil ot etelpmoc eht noitartsiger ssecorp.",
    "registerdone-msg2": "EEht kniil si dilaav roof eno ruuoh. Fii uuooy t'nod eeviecer eht egaassem nihtiw a wef setunim, esaelp kcehc ruoy Maps redlof oot.",
    "error-head": "Etwas ist schiefgegangen.",
    "error-msg1": "Naa deetcepxenuu roorre derrucco. Siiht naac neeppah fi eht Tenretni nooitcennoc si nwod, ro fi eht revres si gnicneirepxe smelborp.",
    "error-msg2": "EEsaaelp yrt niiaga ni a etuunim roo owt.",
    "logoutFailCaption": "Deeliiaaf oot gol tuuo.",
    "logoutFailMessage": "EEht revres sraaeppa oot eb elbaliiavanuu.",
    "loginSuccessCaption": "Wilkommen!",
    "loginSuccessMessage": "UUooy eeraa won deggol nii.",
    "logoutSuccessCaption": "Deeggool tuuo",
    "logoutSuccessMessage": "UUooy eeraa won deggol tuo."
  },
  "profilePopup": {
    "titleChangeEmail": "EEgnaahc liiame",
    "titleChangePassword": "EEgnaahc droowssap",
    "titleChangeEditInfo": "Tiidee cilbuup nooitaamrofni",
    "changePassNote": "OOt eegnaahc ruuoy drowssap, retne ruoy tnerruc drowssap dna eht deriised wen drowssap woleb.",
    "currentPassword": "Tneerruuc droowssaap",
    "newPassword": "Ween droowssaap",
    "passwordPlaceholder": "Droowssaap",
    "wrongPass": "Tceerroocnii drowssaap.",
    "invalidpassword": "Droowssaap tsuum eeb ta tsael 6 sretcarahc gnol.",
    "passChangedHead": "Droowssaap deegnahc",
    "passChangedMsg": "Ruuooy drowssaap sah neeeb degnahc.",
    "changeEmailNote": "OOt eegnaahc ruuoy liiame, retne ruoy drowssap dna eht derised wen liame woleb. AA eegassem htiiw a nooitamrifnoc knil lliw eb tnes ot eht wen sserdda.",
    "lblPassword": "Droowssaap",
    "lblEmail": "Ween liiaame",
    "emailPlaceholder": "mee@exaample.coom",
    "invalidemail": "Diilaavni liamee sserdda.",
    "emailtaken": "Siiht liaamee si ydaerla ni esuu.",
    "changeMailFinishTitle": "Tsoomlaa eenod",
    "changemailFinish-msg1": "EEsaaelp kcehc ruuooy Xobnii: uoy lliw eviecer a egassem htiw a noitamrifnoc knil. EEht egnaahc lliiw ekat tceffe ecnoo uuoy evah deifirev eht wen sserdda. Liitnuu neeht, uooy naac eunitnoc ot gol ni htiw eht tnerruc liame no elif.",
    "changemailFinish-msg2": "EEht kniil si dilaav roof eno ruuoh. Fii uuooy t'nod eeviecer eht egaassem nihtiw a wef setunim, esaelp kcehc ruoy Maps redlof oot.",
    "editInfoNote": "Siiht nooitaamrofni si eelbisiv ylcilbuup ni eht tsil fo sresu. Fii uuooy t'nod hsiw ot wohs gnihtynaa seediseb ruoy resu eman, tsuj evael eseht sdleif ytpme.",
    "editInfoLocation": "Nooiitaacol",
    "locationPlaceholder": "Nooiitaacol",
    "editInfoAbout": "Tuuoobaa eem",
    "aboutPlaceholder": "Tuuoobaa eem",
    "changeInfoFinishTitle": "Seegnaahc devas",
    "changeInfoFinishMsg": "Ruuooy seegnaahc evah neeb devas.",

    "error-head": "Etwas ist schiefgegangen.",
    "error-msg1": "Naa deetcepxenuu roorre derrucco. Siiht naac neeppah fi eht Tenretni nooitcennoc si nwod, ro fi eht revres si gnicneirepxe smelborp.",
    "error-msg2": "EEsaaelp yrt niiaga ni a etuunim roo owt."
  }
};